"""API routes for the WC26 prediction system.

All prediction endpoints read from ``data/latest_predictions.json``,
which is regenerated by the APScheduler pipeline on a daily cron schedule
(05:00 Asia/Shanghai = 21:00 UTC).  If the cache does not exist yet (first run),
routes fall back to the static ``predictions.json``.
"""

import json
from datetime import datetime
from pathlib import Path

from fastapi import APIRouter, Query
from fastapi.responses import JSONResponse

from models.predictor import predict_match
from pipeline.cron_update import execute_daily_pipeline
from pipeline.backtest import get_backtest_summary
from pipeline.lineup_fetcher import run_lineup_poll, reset_lineup_cache, get_lineup_multipliers
from services.odds_api import get_odds_client

router = APIRouter(prefix="/api", tags=["predictions"])
DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def _load_json(name: str):
    with open(DATA_DIR / name, encoding="utf-8") as f:
        return json.load(f)


def _load_predictions() -> tuple[list[dict], str | None]:
    """Return (predictions_list, updated_at_iso_string).

    Tries ``latest_predictions.json`` first (scheduler cache), then
    falls back to ``predictions.json`` (static snapshot).
    """
    cache_path = DATA_DIR / "latest_predictions.json"
    if cache_path.exists():
        with open(cache_path, encoding="utf-8") as f:
            raw = json.load(f)
        return raw.get("predictions", []), raw.get("updated_at")

    # Fallback
    static_path = DATA_DIR / "predictions.json"
    if static_path.exists():
        with open(static_path, encoding="utf-8") as f:
            return json.load(f), None

    return [], None


def _load_weather_cache() -> list[dict]:
    path = DATA_DIR / "weather_cache.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)
        return raw.get("stadiums", [])
    return []


def _load_injury_cache() -> list[dict]:
    path = DATA_DIR / "injury_cache.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)
        return raw.get("teams", [])
    return []


def _get_cache_metadata() -> dict:
    """Return timestamps from all caches so frontend can show freshness."""
    meta: dict = {
        "predictions_updated_at": None,
        "weather_updated_at": None,
        "injuries_updated_at": None,
        "lineups_updated_at": None,
    }
    for key, filename in [
        ("predictions_updated_at", "latest_predictions.json"),
        ("weather_updated_at", "weather_cache.json"),
        ("injuries_updated_at", "injury_cache.json"),
    ]:
        path = DATA_DIR / filename
        if path.exists():
            with open(path, encoding="utf-8") as f:
                raw = json.load(f)
            meta[key] = raw.get("updated_at")

    # Lineup cache
    lineup_path = DATA_DIR / "lineup_cache.json"
    if lineup_path.exists():
        with open(lineup_path, encoding="utf-8") as f:
            raw = json.load(f)
        meta["lineups_updated_at"] = raw.get("updated_at")
    return meta


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@router.get("/dashboard")
async def get_dashboard():
    """Return the complete dashboard — always from the latest cache."""
    predictions, pred_updated = _load_predictions()
    media = _load_json("media_sentiment.json")
    social = _load_json("social_heat.json")
    rankings = _load_json("fifa_rankings.json")
    stadiums = _load_json("stadium_meta.json")
    cache_meta = _get_cache_metadata()

    # Count live-lineup matches
    live_count = sum(1 for p in predictions if p.get("prediction_status") == "Live-Lineup")

    # Count completed matches (have result)
    completed_count = sum(1 for p in predictions if p.get("result", {}).get("status") == "FT")

    # Sort: today's matches first, then future, then past
    today_str = datetime.utcnow().strftime("%Y-%m-%d")

    def _sort_key(p):
        date = p.get("date", "9999")
        has_result = p.get("result", {}).get("status") == "FT"
        is_today = 0 if date == today_str else (1 if date > today_str else 2)
        return (is_today, date, 0 if has_result else 1)

    predictions.sort(key=_sort_key)

    return {
        "meta": {
            "title": "世界杯2026预测系统",
            "generated_at": pred_updated or datetime.utcnow().isoformat() + "Z",
            "total_teams": 48,
            "total_matches": 104,
            "backtest_accuracy": 0.0,
            "training_samples": 0,
            "live_lineup_count": live_count,
            "completed_count": completed_count,
            "cache": cache_meta,
        },
        "predictions": predictions,
        "media_sentiment": media,
        "social_heat": social,
        "fifa_rankings": rankings,
        "stadiums": stadiums,
    }


@router.get("/predictions")
async def get_predictions():
    """Return all predictions from the scheduler cache."""
    predictions, updated_at = _load_predictions()
    return {"updated_at": updated_at, "count": len(predictions), "predictions": predictions}


@router.get("/predict")
async def predict_single(
    home: str = Query(..., description="Home team name"),
    away: str = Query(..., description="Away team name"),
    stadium: str = Query(default="azteca", description="Stadium ID"),
    date: str = Query(default="2026-06-11", description="Match date YYYY-MM-DD"),
):
    """
    Run a single live prediction (does NOT use cache — computes in real-time).

    Example: /api/predict?home=Brazil&away=Argentina&stadium=azteca&date=2026-06-20
    """
    try:
        result = predict_match(home, away, date, stadium)
        return JSONResponse(content=result)
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})


@router.get("/weather")
async def get_weather():
    """Return the latest weather cache for all stadiums."""
    return _load_weather_cache()


@router.get("/injuries")
async def get_injuries():
    """Return the latest injury / team-status cache."""
    return _load_injury_cache()


@router.get("/stadiums")
async def get_stadiums():
    return _load_json("stadium_meta.json")


@router.get("/media")
async def get_media_sentiment():
    return _load_json("media_sentiment.json")


@router.get("/social")
async def get_social_heat():
    return _load_json("social_heat.json")


@router.get("/cache-status")
async def cache_status():
    """Convenience endpoint: check freshness of every cache."""
    return _get_cache_metadata()


# ---------------------------------------------------------------------------
# Lineup routes — v4.0.0 live starting XI data
# ---------------------------------------------------------------------------

@router.get("/lineups")
async def get_lineups():
    """Return the full lineup cache with all fetched starting XIs."""
    path = DATA_DIR / "lineup_cache.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return {"updated_at": None, "matches": {}, "team_benchmarks": {}}


@router.get("/lineup/{home}/{away}/{date}")
async def get_match_lineup(
    home: str,
    away: str,
    date: str,
):
    """
    Get lineup & multiplier data for a specific match.

    Example: /api/lineup/Mexico/South Africa/2026-06-11
    """
    match_key = f"{date}_{home}_{away}"
    multipliers = get_lineup_multipliers(home, away, match_key)
    return {
        "match_key": match_key,
        "home_team": home,
        "away_team": away,
        "match_date": date,
        **multipliers,
    }


# ---------------------------------------------------------------------------
# Odds routes — v1.0.0 market odds integration (the-odds-api.com)
# ---------------------------------------------------------------------------

@router.get("/odds")
async def get_match_odds():
    """
    Return the latest match odds cache.

    Includes H2H prices, market-implied probabilities,
    and comparison with model predictions.
    """
    path = DATA_DIR / "odds_cache.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return {"updated_at": None, "matches": {}, "outrights": {}}


@router.get("/odds/outrights")
async def get_outright_odds():
    """Return World Cup winner outright odds."""
    path = DATA_DIR / "odds_cache.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)
        return raw.get("outrights", {})
    return {"teams": {}, "top_5": [], "updated_at": None}


@router.get("/odds/{home}/{away}/{date}")
async def get_match_odds_detail(
    home: str,
    away: str,
    date: str,
):
    """
    Get odds for a specific match.

    Example: /api/odds/Canada/Bosnia and Herzegovina/2026-06-12
    """
    match_key = f"{date}_{home}_{away}"
    path = DATA_DIR / "odds_cache.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)
        match_odds = raw.get("matches", {}).get(match_key)
        if match_odds:
            return {"match_key": match_key, **match_odds}
    return {"match_key": match_key, "error": "No odds data for this match"}


# ---------------------------------------------------------------------------
# Admin routes — pipeline control & backtest visibility
# ---------------------------------------------------------------------------

admin_router = APIRouter(prefix="/api/admin", tags=["admin"])


@admin_router.post("/force-refresh")
async def force_refresh():
    """Trigger the full daily pipeline on-demand (e.g. cron-job.org webhook)."""
    try:
        summary = await execute_daily_pipeline()
        return {"status": "ok", "summary": summary}
    except Exception as e:
        return JSONResponse(status_code=500, content={"status": "error", "detail": str(e)})


@admin_router.get("/backtest-history")
async def backtest_history():
    """Return full backtest history including cumulative stats and daily records."""
    path = DATA_DIR / "backtest_history.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return {"updated_at": None, "cumulative": {}, "daily_records": []}


@admin_router.get("/backtest-summary")
async def backtest_summary():
    """Return cumulative backtest summary only."""
    return get_backtest_summary()


@admin_router.post("/force-refresh-lineup")
async def force_refresh_lineup():
    """
    Trigger an immediate lineup polling cycle.

    External cron services (e.g., cron-job.org) should call this endpoint
    every 5 minutes starting 75 minutes before the first match of the day.
    """
    try:
        result = await run_lineup_poll()
        return {
            "status": "ok",
            "summary": result,
            "hint": "If lineups were fetched, re-run POST /api/admin/force-refresh to regenerate predictions with Live-Lineup multipliers.",
        }
    except Exception as e:
        return JSONResponse(status_code=500, content={"status": "error", "detail": str(e)})


@admin_router.post("/live-refresh")
async def live_refresh():
    """
    Lightweight real-time refresh: fetches live results + lineups,
    merges into the prediction cache. Designed to be called every 2-5 min
    during match windows (June 11 – July 19, 2026).

    Much faster than force-refresh (skips weather/injuries/backtest).
    """
    from pipeline.result_fetcher import fetch_live_results

    try:
        # 1. Fetch live results
        live_results = await fetch_live_results()
        results_lookup: dict[str, dict] = {}
        for r in live_results:
            key = f"{r['date']}_{r['home']}_{r['away']}"
            if r.get("status") and r["status"] != "NS":
                results_lookup[key] = r

        # 2. Poll lineups
        lineup_summary = await run_lineup_poll()

        # 3. Refresh odds cache (if API key available)
        odds_fetched = 0
        try:
            client = get_odds_client()
            odds_summary = await client.get_best_odds_summary()
            outright_summary = await client.get_outright_summary()
            odds_cache = {
                "updated_at": datetime.utcnow().isoformat() + "Z",
                "matches": odds_summary,
                "outrights": outright_summary,
            }
            cache_path = DATA_DIR / "odds_cache.json"
            with open(cache_path, "w", encoding="utf-8") as f:
                json.dump(odds_cache, f, ensure_ascii=False, indent=2)
            odds_fetched = len(odds_summary)
        except Exception:
            pass

        # 4. Merge into latest_predictions.json
        predictions, updated_at = _load_predictions()
        modified = 0
        for p in predictions:
            result_key = f"{p['date']}_{p['home']}_{p['away']}"
            if result_key in results_lookup:
                r = results_lookup[result_key]
                if not p.get("result") or p["result"].get("status") != r.get("status"):
                    p["result"] = {
                        "home_score": r.get("home_score"),
                        "away_score": r.get("away_score"),
                        "outcome": r.get("outcome"),
                        "status": r.get("status", "FT"),
                    }
                    modified += 1

        # 4. Write back
        if modified > 0 or lineup_summary.get("lineups_fetched", 0) > 0 or odds_fetched > 0:
            cache_path = DATA_DIR / "latest_predictions.json"
            live_count = sum(1 for p in predictions if p.get("prediction_status") == "Live-Lineup")
            bt_summary_data = {}
            bt_path = DATA_DIR / "backtest_history.json"
            if bt_path.exists():
                with open(bt_path, encoding="utf-8") as f:
                    bt_data = json.load(f)
                cum = bt_data.get("cumulative", {})
                bt_summary_data = {
                    "accuracy": cum.get("accuracy", 0),
                    "total_matches": cum.get("total_matches", 0),
                    "roi": cum.get("roi", 0),
                }

            out = {
                "updated_at": datetime.utcnow().isoformat() + "Z",
                "count": len(predictions),
                "live_lineup_count": live_count,
                "backtest": bt_summary_data,
                "predictions": predictions,
            }
            with open(cache_path, "w", encoding="utf-8") as f:
                json.dump(out, f, ensure_ascii=False, indent=2)

        return {
            "status": "ok",
            "results_fetched": len(live_results),
            "results_completed": len(results_lookup),
            "predictions_modified": modified,
            "odds_fetched": odds_fetched,
            "lineups": lineup_summary,
        }
    except Exception as e:
        return JSONResponse(status_code=500, content={"status": "error", "detail": str(e)})


@admin_router.post("/refresh-odds")
async def refresh_odds():
    """
    Fetch latest odds from the-odds-api.com and cache them.

    Includes match H2H odds and outright winner futures.
    Call every 5-15 minutes during active betting windows.
    """
    try:
        client = get_odds_client()
        odds_summary = await client.get_best_odds_summary()
        outright_summary = await client.get_outright_summary()

        cache = {
            "updated_at": datetime.utcnow().isoformat() + "Z",
            "matches": odds_summary,
            "outrights": outright_summary,
        }

        cache_path = DATA_DIR / "odds_cache.json"
        with open(cache_path, "w", encoding="utf-8") as f:
            json.dump(cache, f, ensure_ascii=False, indent=2)

        return {
            "status": "ok",
            "matches_cached": len(odds_summary),
            "outrights_teams": len(outright_summary.get("teams", {})),
        }
    except Exception as e:
        return JSONResponse(status_code=500, content={"status": "error", "detail": str(e)})


@admin_router.post("/reset-lineups")
async def reset_lineups():
    """Clear all cached lineups (for testing / debugging)."""
    count = reset_lineup_cache()
    return {"status": "ok", "cleared_entries": count, "hint": "Run force-refresh to regenerate baseline predictions."}
