"""API routes for the WC26 prediction system.

All prediction endpoints read from ``data/latest_predictions.json``,
which is regenerated by the APScheduler pipeline on a cron schedule
(default: every 6 hours).  If the cache does not exist yet (first run),
routes fall back to the static ``predictions.json``.
"""

import json
from datetime import datetime
from pathlib import Path

from fastapi import APIRouter, Query
from fastapi.responses import JSONResponse

from models.predictor import predict_match

router = APIRouter(prefix="/api", tags=["predictions"])
DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def _load_json(name: str):
    with open(DATA_DIR / name, encoding="utf-8") as f:
        return json.load(f)


def _load_predictions() -> tuple[list[dict], str | None]:
    """Return (predictions_list, updated_at_iso_string).

    Tries ``latest_predictions.json`` first (scheduler cache), then
    falls back to ``predictions.json`` (static snapshot).
    """
    cache_path = DATA_DIR / "latest_predictions.json"
    if cache_path.exists():
        with open(cache_path, encoding="utf-8") as f:
            raw = json.load(f)
        return raw.get("predictions", []), raw.get("updated_at")

    # Fallback
    static_path = DATA_DIR / "predictions.json"
    if static_path.exists():
        with open(static_path, encoding="utf-8") as f:
            return json.load(f), None

    return [], None


def _load_weather_cache() -> list[dict]:
    path = DATA_DIR / "weather_cache.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)
        return raw.get("stadiums", [])
    return []


def _load_injury_cache() -> list[dict]:
    path = DATA_DIR / "injury_cache.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)
        return raw.get("teams", [])
    return []


def _get_cache_metadata() -> dict:
    """Return timestamps from all caches so frontend can show freshness."""
    meta: dict = {
        "predictions_updated_at": None,
        "weather_updated_at": None,
        "injuries_updated_at": None,
    }
    for key, filename in [
        ("predictions_updated_at", "latest_predictions.json"),
        ("weather_updated_at", "weather_cache.json"),
        ("injuries_updated_at", "injury_cache.json"),
    ]:
        path = DATA_DIR / filename
        if path.exists():
            with open(path, encoding="utf-8") as f:
                raw = json.load(f)
            meta[key] = raw.get("updated_at")
    return meta


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@router.get("/dashboard")
async def get_dashboard():
    """Return the complete dashboard — always from the latest cache."""
    predictions, pred_updated = _load_predictions()
    media = _load_json("media_sentiment.json")
    social = _load_json("social_heat.json")
    rankings = _load_json("fifa_rankings.json")
    stadiums = _load_json("stadium_meta.json")
    cache_meta = _get_cache_metadata()

    return {
        "meta": {
            "title": "世界杯2026预测系统",
            "generated_at": pred_updated or datetime.utcnow().isoformat() + "Z",
            "total_teams": 48,
            "total_matches": 104,
            "backtest_accuracy": 0.0,
            "training_samples": 0,
            "cache": cache_meta,
        },
        "predictions": predictions,
        "media_sentiment": media,
        "social_heat": social,
        "fifa_rankings": rankings,
        "stadiums": stadiums,
    }


@router.get("/predictions")
async def get_predictions():
    """Return all predictions from the scheduler cache."""
    predictions, updated_at = _load_predictions()
    return {"updated_at": updated_at, "count": len(predictions), "predictions": predictions}


@router.get("/predict")
async def predict_single(
    home: str = Query(..., description="Home team name"),
    away: str = Query(..., description="Away team name"),
    stadium: str = Query(default="azteca", description="Stadium ID"),
    date: str = Query(default="2026-06-11", description="Match date YYYY-MM-DD"),
):
    """
    Run a single live prediction (does NOT use cache — computes in real-time).

    Example: /api/predict?home=Brazil&away=Argentina&stadium=azteca&date=2026-06-20
    """
    try:
        result = predict_match(home, away, date, stadium)
        return JSONResponse(content=result)
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})


@router.get("/weather")
async def get_weather():
    """Return the latest weather cache for all stadiums."""
    return _load_weather_cache()


@router.get("/injuries")
async def get_injuries():
    """Return the latest injury / team-status cache."""
    return _load_injury_cache()


@router.get("/stadiums")
async def get_stadiums():
    return _load_json("stadium_meta.json")


@router.get("/media")
async def get_media_sentiment():
    return _load_json("media_sentiment.json")


@router.get("/social")
async def get_social_heat():
    return _load_json("social_heat.json")


@router.get("/cache-status")
async def cache_status():
    """Convenience endpoint: check freshness of every cache."""
    return _get_cache_metadata()
